FROM adoptopenjdk/openjdk16:ubi

LABEL maintainer="Priyanka Giri"

ARG artifact=target/spring-boot-web.jar

WORKDIR /opt/app

COPY ${artifact} app.jar

# This should not be changed
ENTRYPOINT ["java","-jar","/app.jar"]